"""Add donors and documents tables

Revision ID: 7137bc0cb5d2
Revises: dda954b8a858
Create Date: 2025-10-26 11:41:23.898324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7137bc0cb5d2'
down_revision = 'dda954b8a858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if tables exist before creating (idempotent)
    conn = op.get_bind()
    
    # Check if donors table exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'donors'
        )
    """))
    
    if not result.scalar():
        op.create_table('donors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unique_donor_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('is_priority', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
        op.create_index(op.f('ix_donors_unique_donor_id'), 'donors', ['unique_donor_id'], unique=True)
    
    # Check if documents table exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'documents'
        )
    """))
    
    if not result.scalar():
        op.create_table('documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('file_type', sa.String(), nullable=False),
        sa.Column('document_type', sa.Enum('MEDICAL_HISTORY', 'SEROLOGY_REPORT', 'LAB_RESULTS', 'RECOVERY_CULTURES', 'CONSENT_FORM', 'DEATH_CERTIFICATE', 'OTHER', name='documenttype', create_type=False), nullable=True),
        sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'ANALYZING', 'REVIEWING', 'COMPLETED', 'FAILED', 'REJECTED', name='documentstatus', create_type=False), nullable=True),
        sa.Column('azure_blob_url', sa.String(), nullable=True),
        sa.Column('processing_result', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('donor_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_donors_unique_donor_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
