"""Add donors and documents tables

Revision ID: 7137bc0cb5d2
Revises: dda954b8a858
Create Date: 2025-10-26 11:41:23.898324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7137bc0cb5d2'
down_revision = 'dda954b8a858'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if tables exist before creating (idempotent)
    conn = op.get_bind()
    
    # Check if donors table exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'donors'
        )
    """))
    
    if not result.scalar():
        op.create_table('donors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unique_donor_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=True),
        sa.Column('date_of_birth', sa.Date(), nullable=True),
        sa.Column('gender', sa.String(), nullable=False),
        sa.Column('is_priority', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_donors_id'), 'donors', ['id'], unique=False)
        op.create_index(op.f('ix_donors_unique_donor_id'), 'donors', ['unique_donor_id'], unique=True)
    
    # Check if documents table exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'documents'
        )
    """))
    
    if not result.scalar():
        # Create enums if they don't exist (needed before creating table)
        # Check for documenttype enum
        enum_check1 = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'documenttype'
            )
        """))
        
        if not enum_check1.scalar():
            conn.execute(sa.text("""
                CREATE TYPE documenttype AS ENUM (
                    'MEDICAL_HISTORY', 'SEROLOGY_REPORT', 'LAB_RESULTS', 
                    'RECOVERY_CULTURES', 'CONSENT_FORM', 'DEATH_CERTIFICATE', 'OTHER'
                );
            """))
        
        # Check for documentstatus enum
        enum_check2 = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'documentstatus'
            )
        """))
        
        if not enum_check2.scalar():
            conn.execute(sa.text("""
                CREATE TYPE documentstatus AS ENUM (
                    'UPLOADED', 'PROCESSING', 'ANALYZING', 'REVIEWING', 
                    'COMPLETED', 'FAILED', 'REJECTED'
                );
            """))
        
        # Create documents table using raw SQL to avoid SQLAlchemy enum creation issues
        op.execute("""
            CREATE TABLE documents (
                id SERIAL PRIMARY KEY,
                filename VARCHAR NOT NULL,
                original_filename VARCHAR NOT NULL,
                file_size INTEGER NOT NULL,
                file_type VARCHAR NOT NULL,
                document_type documenttype,
                status documentstatus,
                azure_blob_url VARCHAR,
                processing_result TEXT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE,
                donor_id INTEGER NOT NULL REFERENCES donors(id),
                uploaded_by INTEGER NOT NULL REFERENCES users(id)
            );
        """)
        op.execute("CREATE INDEX IF NOT EXISTS ix_documents_id ON documents(id);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_donors_unique_donor_id'), table_name='donors')
    op.drop_index(op.f('ix_donors_id'), table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
