"""add_document_progress_and_status_fields

Revision ID: 965785d01084
Revises: 7137bc0cb5d2
Create Date: 2025-10-26 13:16:40.572685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965785d01084'
down_revision = '7137bc0cb5d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if columns exist before adding (idempotent)
    conn = op.get_bind()
    
    # Check if progress column exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'documents' 
            AND column_name = 'progress'
        )
    """))
    
    if not result.scalar():
        op.add_column('documents', sa.Column('progress', sa.Float(), nullable=True))
    
    # Check if error_message column exists
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = 'documents' 
            AND column_name = 'error_message'
        )
    """))
    
    if not result.scalar():
        op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'progress')
    # ### end Alembic commands ###
