"""add_settings_table

Revision ID: cb292b7f4abc
Revises: 965785d01084
Create Date: 2025-10-26 14:01:34.165817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb292b7f4abc'
down_revision = '965785d01084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Create settingtype enum if it doesn't exist (idempotent)
    conn.execute(sa.text("""
        DO $$ BEGIN
            CREATE TYPE settingtype AS ENUM ('OPENAI_API_KEY', 'OPENAI_EMBEDDING_MODEL', 'OPENAI_SUMMARIZATION_MODEL', 'AZURE_API_KEY', 'AZURE_ENDPOINT', 'AZURE_DEPLOYMENT_ID', 'GOOGLE_API_KEY', 'GOOGLE_PROJECT_ID', 'ANTHROPIC_API_KEY');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))
    
    # Check if settings table exists before creating (idempotent)
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'settings'
        )
    """))
    
    if not result.scalar():
        op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.Enum('OPENAI_API_KEY', 'OPENAI_EMBEDDING_MODEL', 'OPENAI_SUMMARIZATION_MODEL', 'AZURE_API_KEY', 'AZURE_ENDPOINT', 'AZURE_DEPLOYMENT_ID', 'GOOGLE_API_KEY', 'GOOGLE_PROJECT_ID', 'ANTHROPIC_API_KEY', name='settingtype', create_type=False), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('is_encrypted', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
        op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
