"""add_settings_table

Revision ID: cb292b7f4abc
Revises: 965785d01084
Create Date: 2025-10-26 14:01:34.165817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb292b7f4abc'
down_revision = '965785d01084'
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    
    # Check if settings table exists before creating (idempotent)
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'settings'
        )
    """))
    
    if not result.scalar():
        # Check if settingtype enum exists before creating
        enum_check = conn.execute(sa.text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'settingtype'
            )
        """))
        
        if not enum_check.scalar():
            conn.execute(sa.text("""
                CREATE TYPE settingtype AS ENUM (
                    'OPENAI_API_KEY', 'OPENAI_EMBEDDING_MODEL', 'OPENAI_SUMMARIZATION_MODEL', 
                    'AZURE_API_KEY', 'AZURE_ENDPOINT', 'AZURE_DEPLOYMENT_ID', 
                    'GOOGLE_API_KEY', 'GOOGLE_PROJECT_ID', 'ANTHROPIC_API_KEY'
                );
            """))
        
        # Create settings table using raw SQL to avoid SQLAlchemy enum creation issues
        op.execute("""
            CREATE TABLE settings (
                id SERIAL PRIMARY KEY,
                key settingtype NOT NULL,
                value TEXT,
                is_encrypted BOOLEAN,
                description TEXT,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE
            );
        """)
        op.execute("CREATE INDEX IF NOT EXISTS ix_settings_id ON settings(id);")
        op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_settings_key ON settings(key);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
